"""
Eligibility Check Log ORM Model
Records evaluation results generated by the deterministic eligibility engine for audit and transparency.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import uuid

from sqlalchemy import DateTime, ForeignKey, String, Text, JSON, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import Uuid

from app.db.base import Base, UUIDPrimaryKeyMixin, utc_now


class EligibilityCheckLog(Base, UUIDPrimaryKeyMixin):
    """
    Log of a single student-opportunity eligibility evaluation.
    Contains overall status, individual rule outcomes, and generated explanation summary.
    """

    __tablename__ = "eligibility_check_logs"

    student_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("students.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    opportunity_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("opportunities.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    overall_status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )  # ELIGIBLE, NOT_ELIGIBLE, POTENTIALLY_ELIGIBLE, INSUFFICIENT_INFORMATION
    rule_results: Mapped[List[Dict[str, Any]]] = mapped_column(JSON, nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    checked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=utc_now,
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # Relationships
    student: Mapped["Student"] = relationship(
        "Student",
        back_populates="eligibility_logs",
    )
    opportunity: Mapped["Opportunity"] = relationship(
        "Opportunity",
        back_populates="eligibility_logs",
    )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize log entry to dictionary."""
        return {
            "id": str(self.id),
            "student_id": str(self.student_id),
            "opportunity_id": str(self.opportunity_id),
            "overall_status": self.overall_status,
            "rule_results": self.rule_results,
            "summary": self.summary,
            "checked_at": self.checked_at.isoformat() if self.checked_at else None,
        }
